/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cacard_jni_EchoString */

#ifndef _Included_com_cacard_jni_EchoString
#define _Included_com_cacard_jni_EchoString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cacard_jni_EchoString
 * Method:    Echo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cacard_jni_EchoString_Echo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
