
package com.cacard.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://ws.cacard.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param msg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.cacard.com/", className = "com.cacard.ws.server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.cacard.com/", className = "com.cacard.ws.server.SayHelloResponse")
    @Action(input = "http://ws.cacard.com/Hello/sayHelloRequest", output = "http://ws.cacard.com/Hello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "msg", targetNamespace = "")
        String msg);

}
